Repository gii-is-psg2/PSG2-2021-G7-74, pull requests merged in 2021-04, with the labels that each got.

#44 AÑADIDAS DEPENDENCIAS SONAR Y ELIMINACION DE MASTER NIKONIKO
  NikoNiko.md
  pom.xml
Labels: bug, coding

#45 CAMBIOS DE MASTER A DEVELOP (INTEGRACION DE SONAR)
  pom.xml
Labels: coding

#52 Feature/A3.2 b - COMPLETED
  src/main/java/org/springframework/samples/petclinic/repository/HotelBookRepository.java
  src/main/java/org/springframework/samples/petclinic/service/HotelBookService.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/BusyBookException.java
  src/main/java/org/springframework/samples/petclinic/web/HotelBookController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/resources/static/resources/images/oops.jpg
  src/main/webapp/WEB-INF/jsp/dateException.jsp
  src/main/webapp/WEB-INF/jsp/dateExceptionDuplicated.jsp
  src/test/java/org/springframework/samples/petclinic/service/HotelBookServiceTests.java
Labels: coding, enhancement

#49 Feature/a3.2 c COMPLETADA
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Adoptions.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/model/Status.java
  src/main/java/org/springframework/samples/petclinic/repository/AdoptionsRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/service/AdoptionsService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/DuplicatedAdoptionException.java
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/pets/petAdoptionsList.jsp
  src/test/java/org/springframework/samples/petclinic/model/AdoptionsTests.java
  src/test/java/org/springframework/samples/petclinic/service/AdoptionsServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AdoptionsControllerTests.java
Labels: coding, enhancement

#51 Feature/A3.2 a COMPLETADA
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/repository/CauseRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/DonationRepository.java
  src/main/java/org/springframework/samples/petclinic/service/CausesService.java
  src/main/java/org/springframework/samples/petclinic/service/DonationsService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/DuplicatedPetNameException.java
  src/main/java/org/springframework/samples/petclinic/web/CausesController.java
  src/main/java/org/springframework/samples/petclinic/web/DonationsController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/java/org/springframework/samples/petclinic/web/VisitController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/causes/causesDetails.jsp
  src/main/webapp/WEB-INF/jsp/causes/causesList.jsp
  src/main/webapp/WEB-INF/jsp/causes/createOrUpdateCausesForm.jsp
  src/main/webapp/WEB-INF/jsp/causes/findCauses.jsp
  src/main/webapp/WEB-INF/jsp/donation/createOrUpdateDonationForm.jsp
  src/main/webapp/WEB-INF/jsp/owners/createOrUpdateOwnerForm.jsp
  src/main/webapp/WEB-INF/tags/inputField.tag
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/model/CauseTests.java
  src/test/java/org/springframework/samples/petclinic/model/DonationTests.java
  src/test/java/org/springframework/samples/petclinic/service/CausesServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/DonationServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/CausesControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/DonationsControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/HotelBookControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetTypeFormatterTests.java
  src/test/java/org/springframework/samples/petclinic/web/VisitControllerTests.java
Labels: coding, enhancement

#54 Release/v1.1.0
  src/main/java/org/springframework/samples/petclinic/PetclinicApplication.java
  src/main/java/org/springframework/samples/petclinic/configuration/ExceptionHandlerConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/WebConfig.java
  src/main/java/org/springframework/samples/petclinic/model/Adoption.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/repository/AdoptionsRepository.java
  src/main/java/org/springframework/samples/petclinic/service/AdoptionsService.java
  src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/exceptions/DuplicatedAdoptionException.java
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/main/less/responsive.less
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/causes/causesDetails.jsp
  src/main/webapp/WEB-INF/jsp/causes/causesList.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/createOrUpdateVetForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/model/AdoptionsTests.java
  src/test/java/org/springframework/samples/petclinic/service/AdoptionsServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/HotelBookServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AdoptionsControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/CrashControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetControllerTests.java
Labels: enhancement, release
