Repository gii-is-psg2/PSG2-2021-G7-74, pull requests merged in 2021-05, with the labels that each got.

#55 Release/v1.1.1
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Vets.java
  src/main/java/org/springframework/samples/petclinic/repository/AdoptionsRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
  src/main/java/org/springframework/samples/petclinic/service/CausesService.java
  src/main/java/org/springframework/samples/petclinic/service/HotelBookService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/util/EntityUtils.java
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/java/org/springframework/samples/petclinic/web/CrashController.java
  src/main/java/org/springframework/samples/petclinic/web/HotelBookController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/main/less/petclinic.less
  src/main/less/responsive.less
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/model/AdoptionsTests.java
  src/test/java/org/springframework/samples/petclinic/model/CauseTests.java
  src/test/java/org/springframework/samples/petclinic/model/DonationTests.java
  src/test/java/org/springframework/samples/petclinic/model/HotelBookTests.java
  src/test/java/org/springframework/samples/petclinic/model/ValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/service/AdoptionsServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/CausesServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/DonationServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/HotelBookServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/VetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AdoptionsControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/CausesControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/HotelBookControllerTests.java
Labels: enhancement, release

#56 Release/v1.1.1 (develop)
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Owner.java
  src/main/java/org/springframework/samples/petclinic/model/Vets.java
  src/main/java/org/springframework/samples/petclinic/repository/AdoptionsRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/VisitRepository.java
  src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
  src/main/java/org/springframework/samples/petclinic/service/CausesService.java
  src/main/java/org/springframework/samples/petclinic/service/HotelBookService.java
  src/main/java/org/springframework/samples/petclinic/service/OwnerService.java
  src/main/java/org/springframework/samples/petclinic/service/PetService.java
  src/main/java/org/springframework/samples/petclinic/util/EntityUtils.java
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/java/org/springframework/samples/petclinic/web/CrashController.java
  src/main/java/org/springframework/samples/petclinic/web/HotelBookController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/main/less/petclinic.less
  src/main/less/responsive.less
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/model/AdoptionsTests.java
  src/test/java/org/springframework/samples/petclinic/model/CauseTests.java
  src/test/java/org/springframework/samples/petclinic/model/DonationTests.java
  src/test/java/org/springframework/samples/petclinic/model/HotelBookTests.java
  src/test/java/org/springframework/samples/petclinic/model/ValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/service/AdoptionsServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/CausesServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/DonationServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/HotelBookServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/VetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AdoptionsControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/CausesControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/HotelBookControllerTests.java
Labels: enhancement, release

#79 Feature A4.2.1 - IMPLEMENTACION ENDPOINT
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
Labels: coding

#80 Feature A4.2.2 Release
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
Labels: release

#87 I-000931 - RESUELTA
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
Labels: Incident, coding

#89 I-000930 Corregida
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateHotelBookForm.jsp
Labels: Incident, coding, enhancement

#91 I-000929 - INCIDENCIA CORREGIDA
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
Labels: Incident, coding, enhancement

#93 R-000939 - COMPLETADA
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
Labels: Service Request

#99 R-000938 - PETICION DE USUARIO AÑADIDA
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: Service Request, coding

#96 I-000926 - Eliminado el boton para ver en xml
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
Labels: Incident, coding

#101 R-000936 - COMPLETADA
  src/main/less/customstyle.less
  src/main/resources/static/resources/images/github.png
  src/main/webapp/WEB-INF/tags/pivotal.tag
Labels: Service Request, coding, enhancement

#100 R-000934 - Terminada nueva feature, mensaje de no hay donaciones
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/causes/causesDetails.jsp
  src/test/java/org/springframework/samples/petclinic/web/AdoptionsControllerTests.java
Labels: Service Request, coding, enhancement

#104 I-000927 API Health AHORA MUESTRA LOS DETALLES
  src/main/resources/application.properties
Labels: Incident, coding, enhancement

#107 R-000932 Validación formulario visita
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
Labels: Service Request, coding, enhancement

#109 I-000928 - Arreglado palabras sin traducir al español
  src/main/resources/messages/messages_es.properties
Labels: Incident, coding

#110 R-000933 - MENSAJE AL NO HABER ADOPCIONES
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
Labels: Service Request, coding, enhancement

#111 Release/v1.3.0
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/less/customstyle.less
  src/main/resources/application.properties
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/resources/static/resources/images/github.png
  src/main/webapp/WEB-INF/jsp/adoptions/adoptionList.jsp
  src/main/webapp/WEB-INF/jsp/causes/causesDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdateHotelBookForm.jsp
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/pivotal.tag
  src/test/java/org/springframework/samples/petclinic/web/AdoptionsControllerTests.java
Labels: release

#113 RELEASE 1.3.0 - DEVELOP
  src/main/java/org/springframework/samples/petclinic/web/AdoptionsController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/webapp/WEB-INF/jsp/pets/createOrUpdatePetForm.jsp
Labels: release

#114 FEATURE/E.4.3 - REALIZADA PAGINA DE SOPORTE USANDO ITOP API
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Contact.java
  src/main/java/org/springframework/samples/petclinic/web/ITopController.java
  src/main/less/responsive.less
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/itop.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: coding

#115 Release/v1.4.0 - Integración iTop API con página de contacto
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Contact.java
  src/main/java/org/springframework/samples/petclinic/web/ITopController.java
  src/main/less/responsive.less
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/itop.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: coding
